// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3I11OtqPO-q-Efy4CfVDXF2mkQKaXg2s',
    appId: '1:871037738450:android:31a8c5b9db6efbe1397c0b',
    messagingSenderId: '871037738450',
    projectId: 'chat-on-7db94',
    storageBucket: 'chat-on-7db94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT9w9ynsCOqQsV5b4eA_VfLtHJb3OWWPU',
    appId: '1:871037738450:ios:92b0e3b98340eae0397c0b',
    messagingSenderId: '871037738450',
    projectId: 'chat-on-7db94',
    storageBucket: 'chat-on-7db94.appspot.com',
    androidClientId:
        '871037738450-khher76f2bca1arpd3sgqotm55m2va3m.apps.googleusercontent.com',
    iosClientId:
        '871037738450-plulpahjigh1lott1li2adq5m1igerqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatOn',
  );
}
